### ISSUE TITLE
LLM approach for synthetic query generation not using specified prompt

### ISSUE THREAD

**Issue by WJ44** [stanford-futuredata/ARES#58]
For the LLM approach, as opposed to the API approach, the synthetic query and answer generation does not seem to use the specified prompt, only the few-shot examples. Is this intended behaviour?

**Comment by robbym-dev** [comment]
Hi @WJ44,

Thank you for your interested in ARES! 

Yes, this is intended behavior. In the LLM approach, we do not use the specified prompt because few-shot examples are more effective at helping the model generalize and adapt to various tasks. Using examples instead of a prompt reduces the need for extensive prompt engineering and enhances the model's performance by providing richer contextual information.

Please let us know if you have any other questions, thank you!
