### ISSUE TITLE
OutOfMemoryError when Running Example Code with ARES

### ISSUE THREAD

**Issue by chienyutseng** [stanford-futuredata/ARES#61]
I encountered an OutOfMemoryError while attempting to run the example code provided with the ARES evaluation library. The error occurs when the system tries to allocate an additional 64.00 MiB of memory, indicating that the available GPU memory is insufficient.

I am seeking advice on how to configure or optimize computational resources to resolve this memory shortage without degrading model performance. Are there recommended practices, or should adjustments be made in the code or configuration to reduce memory consumption?

Thanks!

### Code Snippet

```
import os
from ares import ARES

ppi_config = {
    "evaluation_datasets": ['nq_unlabeled_output_sub1.tsv'], ## extract 20 samples from nq_unlabeled_output.tsv
    "few_shot_examples_filepath": "nq_few_shot_prompt_for_judge_scoring.tsv",
    "model_choice": "meta-llama/Llama-2-7b-chat-hf",
    "labels": ["Context_Relevance_Label"],
    "gold_label_paths": ["nq_labeled_output_sub1.tsv"],
    "checkpoints": ["Context Relevance Label Joint.pt"],
    "assigned_batch_size": 1000
}

ares = ARES(ppi_config)
results = ares.evaluate_RAG()
print(results)
```

### Simplified nvidia-smi Output
```
GPU 0: NVIDIA GeForce RTX 3090 Ti
- Usage: 24 MiB / 24564 MiB
- Temperature: 39C
- Power Usage: 121W / 450W
```

**Comment by robbym-dev** [comment]
Hi @chienyutseng,

Thank you for reaching out. It seems you are encountering an OutOfMemoryError due to insufficient GPU memory on your NVIDIA GeForce RTX 3090 Ti. This GPU may not have the necessary resources to deploy the checkpoint effectively.

For more information on the required hardware specifications, please refer to the appendix in our guide [here](https://github.com/stanford-futuredata/ARES?tab=readme-ov-file#appendix).

If you need further assistance, feel free to ask!
